### ISSUE TITLE
undefined method `function_is_bool'

### ISSUE THREAD

**Issue by mengesb** [proletaryo/puppet-nagios-nrpe#12]
I'm getting the error message:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: undefined method `function_is_bool' for Scope(Class[Nrpe]):Puppet::Parser::Scope at /etc/puppet/modules/nrpe/manifests/init.pp:65 on node
```

When I look at that line in the module:
```
validate_bool($enable, $dont_blame_nrpe, $opsview_use)
```

Now, I've used validate_bool lots, and it is very odd that I'm getting this now especially against such a simple thing.

I'm using the module in this manner:

```
class { 'nrpe':
  ensure        => running,
  allowed_hosts => [
    'nagios-01.<REDACTED_DOMAIN>',
    'nagios-02.<REDACTED_DOMAIN>',
    'nagios-03.<REDACTED_DOMAIN>'],
  service_check_command => {
    'check_load'       => '/usr/lib/nagios/plugins/check_load -w 15,10,5 -c 30,25,20',
    'check_sys_disk'   => '/usr/lib/nagios/plugins/check_disk -w 20% -c 10% -p /',
    'check_raid'       => '/usr/lib/nagios/plugins/check_raid',
    'check_<REDACTED>' => '/usr/lib/nagios/plugins/check_procs -u root -a <REDACTED> -c 1:1',
  },
  enable        => true,
  before        => Vcsrepo['custom_nagios_checks'],
}
```

Module information:
proletaryo-nrpe (v1.3.0)
puppetlabs-stdlib (v4.5.0)

OS: Debian 7.7
Puppet: 3.7.3-1puppetlabs1

**Comment by mengesb** [comment]
Well; apparently during an upgrade of my tree the full suite of stdlib didn't get commited (new files were left out). Very sorry for this... I was baffled for a long time until I checked my git tree on a new master.

**Comment by proletaryo** [comment]
no problem. I'm glad you resolved it right away :)
